server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://1p.inas.club:15432/java-project-demo
    username: chedejun
    password: 123456
    driver-class-name: org.postgresql.Driver

state-machine:
  ddl-auto: update
  management:
    enabled: true
  console:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,state-machines
